import LocalizedStrings from "react-native-localization";
export default localization = new LocalizedStrings({
    en: {
        tripCost:'Trip Cost',
        accept:'accept',
        refuse:'refuse',
        newOrders:'New',
        previousOrders:'Finished',
        currentOrders:'Curent',
        package:'package',
        packageDetails:'Package Details',
        ship:'ship',
        transport:'transport',
        notes:'notes',
        whatUWant:'What you want?',
        private:'Private',
        shared:'shared',
        vehicleType:'vehicleType',
        motorbike:'motorbike',
        truck:'Truck',
        tank:'Tank',
        dayana:'Dayana',
        packageTreatment:'Package Treatment',
        envelope:'envelope',
        breakable:'breakable',
        cold:'cold',
        help:'help',
        preserve:'preserve',

        arrivalDate:'Arrival Date',
        travelDetails:'Travel Details',
        agree:'Agree',
        goingComingBack:'Going-coming back',
        going:'Going',
        goingFrom:'Source',
        backTo:'Destination',
        numberOfPersons:'Number of persons',
        specialDicount:'Special Discount',
        Promocode:'Promocode',
        myBooks:'My Books',
        currentBooks:'Currnt Books',
        previousBooks:'Previous Books',
        travelType:'Travel Type',
        sourceDestination:'Source and Destination',
        travelNumber:'Travel Number',
        callUs:'Call Us',
        userName:'username',
        phoneNumber:'phone number',
        messege:'Messege',
        send:'Send',
        chat:'Chat',
        typeMessege:'type a messege..',
        termsConditions:'Terms and Conditions',
        ordinary:'Ordinary',
        ordinaryDesc:'Standerd bus - without meal',
        classic:'Classic',
        classicDesc:'Special bus - with a meal',
        gold:'Gold',
        excellent:'Excellent bus - Flight',
        goldDesc:'with a special meal',
        bill:'bill',
        date:'Date',
        day:'Day',
        travelCost:'Travel Cost',
        bookNumber:'Book Number',
        payment:'Payment',
        choosePaymentMethod:'Choose Payment Method',
        signIn:'Sign in',
        email:'Email',
        country:'Country',
        city:'City',
        address:'Address',
        password:'Password',
        next:'Next',
        login:'Login',
        skipLogin:'Skip Login',
        newMember:'New Member',
        thanks:'Thank You',
        finishBook:'For Finishin your Order',
        willBeContact:'And we will contact you soon',
        forgetPassword:'Forget password',
        home:'Home',
        profile:'Profile',
        books:'Books',
        settings:'Settings',
        exit:'Exit',
        fruits:'Fruits',
        call:'Call',
        share:'Share',
        favourit:'Favourit',
        orders:'orders',
        description:'description',
        category:'category',
        addImage:'Add Image',
        delete:'delete',
        myAds:'My Ads',
        addNewAds:'New Ads',
        language: 'Language',
        save: 'Save',
        confirmPassword:'confirm password',
        confirmPasswordError:'confirm password should match the password',
        register:'Register',
        selectImage:'please select an Image',
        rial:'Rial',
        pleaseLoginToAddAds:'Please Login First To Add New Advertisments',
        quantity:'Quantity',
        price:'Price',
        adsName:'advertiser name',
        arabic:'arabic',
        english:'english',
        changeLang:'Change Language',
        personalSettings:'Personal Settings',
        updatePassword:'Update Password',
        editImage:'Edit Image',
        usernameError:'you have to enter username',
        emailError:'you have to enter email',
        phoneError:'you have to enter phone',
        countryError:'you have to enter country',
        cityError:'you have to enter city',
        addressError:'you have to enter address',
        passwordError:'you have to enter password',
        passwordConfirmError:'you have to enter passwordConfirm',
        photoError:'you have to enter photo',
        priceError:'you have to enter price',
        catError:'you have to enter category',
        desError:'you have to enter description',
        quantityError:'you have to enter quantity',
        nameError:'you have to enter name',
        addressError:'you have to enter address',
        cityError:'you have to choose city',
        CountryError:'you have to choose country',
        addAds:"Add Advertisment",
        kilo:'kilo',
        update:'update',
        updated:'updated successfully',
        deleted:'Advertiser deleted successfully',
        added:' advertisment added succfully',
        languageUpdated:'please refresh app to apply changes',




        selectImage:'please select an Image'
    },
    ar: {
        tripCost:'تكلفة الرحلة',
        accept:'قبول',
        refuse:'رفض',
        newOrders:'جديدة',
        previousOrders:'تم التسليم',
        currentOrders:'حالية',
        package:'الطرد',
        packageDetails:'تفاصيل الشحنة',
        ship:'شحن',
        transport:'نقل',
        notes:'ملاحظات',
        whatUWant:'ما الذي تريده؟',
        private:'خاص',
        
        shared:'مشترك',
        vehicleType:'نوع المركبة؟',
        motorbike:'دراجة نارية',
        truck:'شاحنة',
        tank:'دباب',
        dayana:'ديانا',
        packageTreatment:'التعامل مع الطرد',
        envelope:'ظرف',
        breakable:'قابل للكسر',
        cold:'بارد',
        help:'مساعدة',
        preserve:'حافظة',
        
        arrivalDate:'تاريخ العودة',
        travelDetails:'تفاصيل الرحلة',
        agree:'موافق',
        goingComingBack:'ذهاب وعودة',
        going:'ذهاب',
        goingFrom:'قيام من',
        backTo:'وصول الي',
        numberOfPersons:'عدد الافراد',
        specialDicount:'خصم خاص',
        Promocode:'بروموكود',
        myBooks:'حجوزاتي',
        currentBooks:'حجوزاتي الحالية',
        previousBooks:'حجوزاتي السابقة',
        travelType:'نوع الرحلة',
        sourceDestination:'القيام والوصول',
        travelNumber:'رقم الرحلة',
        callUs:'اتصل بنا',
        userName:'اسم المستخدم',
        phoneNumber:'رقم الهاتف',
        messege:'رسالة',
        send:'ارسال',
        chat:'المحادثه',
        typeMessege:'ادخل الرسالة',
        termsConditions:'الشروط والحقوق',
        ordinary:'عادية',
        ordinaryDesc:'باص عادي - بدون وجبه',
        classic:'كلاسيك',
        classicDesc:'باص مميز - مع وجبه',
        gold:'ذهبي',
        excellent:'باص فاخر - طيران',
        goldDesc:'مع وجبه مميزه',
        bill:'فاتورة',
        date:'تاريخ',
        day:'اليوم',
        travelCost:'تكلفة الرحلة',
        bookNumber:'رقم الحجز',
        payment:'الدفع',
        choosePaymentMethod:'اختر وسيله للدفع',
        signIn:'تسجيل الدخول',
        email:'البريد الالكتورني',
        country:'الدولة',
        city:'المدينة',
        address:'العنوان',
        password:'كلمة المرور',
        next:'التالي',
        login:'دخول',
        skipLogin:'تخطي التسجيل',
        newMember:'عضو جديد',
        thanks:'نشكركم',
        finishBook:'علي إتمام الحجز',
        willBeContact:'وسيتم التواصل معكم',
        forgetPassword:'نسيت كلمة المرور',
        home:'الرئيسية',
        profile:'الشخصية',
        books:'الحجوزات',
        settings:'الأعدادت',
        exit:'خروج',
        fruits:'فواكه',
        call:'اتصال',
        share:'مشاركة',
        favourit:'مفضلة',
        orders:'الطلبات',
        description:'الوصف',
        category:'الفئة',
        addImage:'اضف صوره',
        delete:'مسح',
        myAds:'اعلاناتي',
        addNewAds:'أضف اعلان',
        language: 'اللغه',
        save: 'حفظ',
        confirmPassword:'تأكيد كلمة المرور',
        confirmPasswordError:"كلمة المرور غير متطابقة",
        register:'تسجيل',
        selectImage:'اختر صورة من فضلك',
        rial:'ريال',
        pleaseLoginToAddAds:'من فضلك قم بتسجيل الدخول اولا لكي تستطيع اضافه اعلان',
        quantity:'الكمية',
        price:'السعر',
        adsName:'اسم الاعلان',
        arabic:'عربي',
        english:'انجليزي',
        changeLang:'تغيير اللغة',
        personalSettings:'اعدادات شخصية',
        updatePassword:'تجديد كلمة المرور',
        editImage:'تعديل الصورة',
        usernameError:'هذا الحقل مطلوب',
        emailError:'هذا الحقل مطلوب',
        phoneError:'هذا الحقل مطلوب',
        countryError:'هذا الحقل مطلوب',
        cityError:'هذا الحقل مطلوب',
        addressError:'هذا الحقل مطلوب',
        passwordError:'هذا الحقل مطلوب',
        passwordConfirmError:'هذا الحقل مطلوب',
        photoError:'هذا الحقل مطلوب',
        passwordConfirmErrorError:'هذا الحقل مطلوب',
        priceError:'هذا الحقل مطلوب',
        catError:'هذا الحقل مطلوب',
        desError:'هذا الحقل مطلوب',
        quantityError:'هذا الحقل مطلوب',
        nameError:'هذا الحقل مطلوب',
        addressError:'هذا الحقل مطلوب',
        cityError:'هذا الحقل مطلوب',
        CountryError:'هذا الحقل مطلوب',
        addAds:"اضف اعلان",
        kilo:'كيلو',

        update:'تحديث',
        updated:'تم التحديث بنجاح',
        deleted:'تم حذف الاعلان بنجاح ',
        added:'تم اضافة الاعلان بنجاح',
        languageUpdated:'من فضلك اعد فتح التطبيق حتي يتم تحديث التغيرات',


        selectImage:'اختر صورة من فضلك'
    }
})
